#!/bin/bash
# Example script to run episodic simulation
# This demonstrates the usage of the episodic simulation system

echo "====================================================="
echo "Episodic Simulation System - Usage Examples"
echo "====================================================="
echo ""
echo "This system allows you to run the Gazebo simulation"
echo "repeatedly for a specified number of episodes."
echo ""
echo "Basic usage (10 episodes, 60 seconds each):"
echo "  ros2 launch turtlebot_simulation episodic_simulation.launch.py"
echo ""
echo "Custom number of episodes:"
echo "  ros2 launch turtlebot_simulation episodic_simulation.launch.py num_episodes:=20"
echo ""
echo "Custom episode duration (30 seconds):"
echo "  ros2 launch turtlebot_simulation episodic_simulation.launch.py episode_duration:=30.0"
echo ""
echo "Run without GUI (faster):"
echo "  ros2 launch turtlebot_simulation episodic_simulation.launch.py gui:=false"
echo ""
echo "Custom output file:"
echo "  ros2 launch turtlebot_simulation episodic_simulation.launch.py output_file:=/tmp/scores.txt"
echo ""
echo "Combined example (5 episodes, 45 seconds each, no GUI):"
echo "  ros2 launch turtlebot_simulation episodic_simulation.launch.py num_episodes:=5 episode_duration:=45.0 gui:=false"
echo ""
echo "====================================================="
echo "Output Format"
echo "====================================================="
echo ""
echo "The scores are saved to episode_scores.txt by default"
echo "in CSV format with the following structure:"
echo ""
echo "  # Episode Scores - Generated at <timestamp>"
echo "  # Total episodes: <N>"
echo "  # Episode duration: <seconds> seconds"
echo "  # Format: episode_number,score"
echo "  1,15.234567"
echo "  2,14.876543"
echo "  3,16.123456"
echo "  ..."
echo ""
echo "====================================================="
