/**:
  ros__parameters:
    use_stamped: false
    topics:
      joy:
        topic: cmd_vel_joy
        timeout: 0.5
        priority: 10
      keyboard:
        topic: cmd_vel_keyboard
        timeout: 0.5
        priority: 5
      navigation:
        topic: cmd_vel_nav
        timeout: 0.5
        priority: 1

